use anyhow::{Result, anyhow};
use std::io::{PipeReader, Read};
use std::os::unix::process::CommandExt;
use std::process::{self, ExitStatus};
use std::thread;
use std::time::Duration;

type TimeoutKill = bool;

pub trait CommandExec {
    /// Spawns child and returns raw data for streaming. Timeout is not handled.
    fn stream(self) -> Result<(process::Child, PipeReader), String>;
    /// Spawns child, waits for output with optional timeout, and returns output.
    fn run(self, timeout: Option<Duration>) -> Result<String, String>;
}

pub trait ChildWait {
    /// Custom method for waiting for a child with optional timeout, based on `wait_timeout::ChildExt`.
    fn wait_timeout(&mut self, timeout: Option<Duration>) -> Result<(TimeoutKill, ExitStatus)>;
}

impl CommandExec for process::Command {
    /// Executes command in a child process and returns child and output reader for streaming.
    ///
    /// Pipes `stderr` into `stdout` and returns a string-based error on error.
    ///
    /// Note: This function takes ownership of the command, because the command
    /// must be dropped after piping `stderr` - otherwise, a deadlock would occur.
    /// This means that one cannot pass in a `&mut self` which is generated by chaining functions.
    ///
    /// More information here: https://doc.rust-lang.org/std/io/fn.pipe.html
    fn stream(self) -> Result<(process::Child, PipeReader), String> {
        let program = self.get_program().to_str().unwrap().to_owned();
        let (reader, writer) =
            std::io::pipe().map_err(|e| format!("Failed to create pipe: {e}"))?;
        let cloned_writer = writer
            .try_clone()
            .map_err(|e| format!("Failed to clone pipe: {e}"))?;

        let mut command = self;
        command.stdout(writer).stderr(cloned_writer);
        let child = command
            // group processes so we can kill grandchildren
            // process group id would be same as the child pid
            .process_group(0)
            .spawn()
            .map_err(|e| format!("Failed to spawn '{program}': {e}"))?;
        drop(command);

        Ok((child, reader))
    }

    /// Executes command in a child process, waits for output with an optional timeout, and returns output.
    fn run(self, timeout: Option<Duration>) -> Result<String, String> {
        let program = self.get_program().to_str().unwrap().to_owned();

        let (mut child, mut reader) = self.stream()?;

        let t = thread::spawn(move || -> Result<String, String> {
            let mut buf = String::new();
            reader
                .read_to_string(&mut buf)
                .map_err(|e| format!("Unable to process output: {e}"))?;
            Ok(buf.trim().to_owned())
        });

        let (timeout_kill, status) = ChildWait::wait_timeout(&mut child, timeout)
            .map_err(|e| format!("Failed to wait for '{program}': {e}"))?;

        let mut output = t.join().unwrap()?;
        if timeout_kill {
            output += "\nTimeout";
        }
        match status.success() {
            true => Ok(output),
            false => Err(output),
        }
    }
}

impl ChildWait for process::Child {
    /// Waits for the child to exit with an optional timeout,
    /// returns whether child is timeout-killed and its exit status.
    fn wait_timeout(&mut self, timeout: Option<Duration>) -> Result<(TimeoutKill, ExitStatus)> {
        match timeout {
            None => Ok((false, self.wait()?)),
            Some(dur) => match wait_timeout::ChildExt::wait_timeout(self, dur) {
                Ok(Some(status)) => Ok((false, status)),
                Ok(None) => {
                    unsafe {
                        // kill process group (which includes grandchildren)
                        // just self.child() is not enough since grandchildren can hold FD
                        libc::kill(-(self.id() as i32), libc::SIGKILL);
                    }
                    Ok((true, self.wait()?))
                }
                Err(e) => Err(anyhow!(e)),
            },
        }
    }
}
