use anyhow::Result;
use std::io::Read;
use std::process;

pub trait Exec {
    fn run(self) -> Result<String, String>;
}

impl Exec for process::Command {
    /// Executes command in a child process and returns parsed output.
    ///
    /// `stderr` is piped into `stdout` and a string-based error is returned on error.
    ///
    /// Note: This function takes ownership of the command, because the command
    /// must be dropped after piping `stderr` - otherwise, a deadlock would occur.
    /// This means that one cannot pass in a `&mut self` which is generated by chaining functions.
    fn run(self) -> Result<String, String> {
        let program = self.get_program().to_str().unwrap().to_owned();
        let (mut reader, writer) =
            std::io::pipe().map_err(|e| format!("Failed to create pipe: {e}"))?;
        let cloned_writer = writer
            .try_clone()
            .map_err(|e| format!("Failed to clone pipe: {e}"))?;

        let mut command = self;
        command.stdout(writer).stderr(cloned_writer);
        let mut child = command
            .spawn()
            .map_err(|e| format!("Failed to spawn '{program}': {e}"))?;
        drop(command);

        let mut buf = String::new();
        reader
            .read_to_string(&mut buf)
            .map_err(|e| format!("Unable to process output: {e}"))?;

        let status = child
            .wait()
            .map_err(|e| format!("Failed to execute '{program}': {e}"))?;

        let output = buf.trim();
        if !status.success() {
            return Err(format!("Command '{program}' did not succeed: {output}"));
        }
        Ok(output.to_owned())
    }
}
